# -*- MakeFile -*-

client: tftp_client.c client_ack.c client_error.c client_queries.c client.h client_utils.h
	gcc tftp_client.c client_ack.c client_error.c client_queries.c client.h client_utils.h -o client
