# -*- MakeFile -*-

server: tftp_server.c server_ack.c server_error.c server_queries.c server.h server_utils.h
	gcc tftp_server.c server_ack.c server_error.c server_queries.c server.h server_utils.h -o server